package practicahibernate;
// Generated 02-feb-2021 10:12:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private Colegio colegio;
     private String codDep;
     private String nombre;
     private String tipo;
     private String numeroIntegrantes;
     private String plantaLocalizacion;
     private Set profesors = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, Colegio colegio, String codDep) {
        this.idDepartamento = idDepartamento;
        this.colegio = colegio;
        this.codDep = codDep;
    }
    public Departamento(int idDepartamento, Colegio colegio, String codDep, String nombre, String tipo, String numeroIntegrantes, String plantaLocalizacion/*, Set profesors*/) {
       this.idDepartamento = idDepartamento;
       this.colegio = colegio;
       this.codDep = codDep;
       this.nombre = nombre;
       this.tipo = tipo;
       this.numeroIntegrantes = numeroIntegrantes;
       this.plantaLocalizacion = plantaLocalizacion;
      // this.profesors = profesors;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Colegio getColegio() {
        return this.colegio;
    }
    
    public void setColegio(Colegio colegio) {
        this.colegio = colegio;
    }
    public String getCodDep() {
        return this.codDep;
    }
    
    public void setCodDep(String codDep) {
        this.codDep = codDep;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumeroIntegrantes() {
        return this.numeroIntegrantes;
    }
    
    public void setNumeroIntegrantes(String numeroIntegrantes) {
        this.numeroIntegrantes = numeroIntegrantes;
    }
    public String getPlantaLocalizacion() {
        return this.plantaLocalizacion;
    }
    
    public void setPlantaLocalizacion(String plantaLocalizacion) {
        this.plantaLocalizacion = plantaLocalizacion;
    }
    public Set getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set profesors) {
        this.profesors = profesors;
    }




}


