package practicahibernate;
// Generated 02-feb-2021 10:12:54 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private Departamento departamento;
     private String dni;
     private String nombre;
     private String apellido;
     private String fechaNacimiento;
     private String sexo;

    public Profesor() {
    }

	
    public Profesor(int idProfesor, Departamento departamento, String dni) {
        this.idProfesor = idProfesor;
        this.departamento = departamento;
        this.dni = dni;
    }
    public Profesor(int idProfesor, Departamento departamento, String dni, String nombre, String apellido, String fechaNacimiento, String sexo) {
       this.idProfesor = idProfesor;
       this.departamento = departamento;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
    }
   
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


